load('./data/sync2.mat')
subplot(2,1,1)
plot(tk,uk,'r',tk,xk(:,1:4),'b')
xlabel('Time (s)')
ylabel('Pressures (Pa)')
legend('Commanded Pressures','Actual Pressures')
subplot(2,1,2)
plot(tk,xk(:,7),'r',tk,xk(:,8),'b')
xlabel('Time (s)')
ylabel('Kinematic Position (rad)')
legend('U','V')